Name: jolla-settings-screenmonitor
Summary: jolla-settings-screenmonitor
Version: 1.0.6
Release: 1
# The contents of the Group field should be one of the groups listed here:
# http://gitorious.org/meego-developer-tools/spectacle/blobs/master/data/GROUPS
Group: Applications/System
URL: http://me.medesimo.eu
License: GPL2
# This must be generated before uploading a package to a remote build service.
# Usually this line does not need to be modified.
Sources:
- '%{name}-%{version}.tar.bz2'
Description: |
  A simple screen usage monitor for Sailfish OS
Configure: none
# The qtc5 builder inserts macros to allow QtCreator to have fine
# control over qmake/make execution
Builder: qtc5

# This section specifies build dependencies that are resolved using pkgconfig.
# This is the preferred way of specifying build dependencies for your package.
PkgConfigBR:
  - sailfishapp >= 1.0.2
  - Qt5Core
  - Qt5Qml
  - Qt5Quick
  - gobject-2.0

# Build dependencies without a pkgconfig setup can be listed here
PkgBR:
   - vala

# Runtime dependencies which are not automatically detected
Requires:
  - sailfishsilica-qt5 >= 0.10.9
  - nemo-qml-plugin-contextkit-qt5

# All installed files
Files:
  - '%{_bindir}/ScreenMonitor'
  - '%{_sysconfdir}/dbus-1'
  - '%{_datadir}/dbus-1'
  - '%{_datadir}/jolla-settings'
  - '%{_unitdir}/ScreenMonitor.service'

# For more information about yaml and what's supported in Sailfish OS
# build system, please see https://wiki.merproject.org/wiki/Spectacle

